import Head from 'next/head';
import Image from 'next/image';


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio WebPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" 
        href="/tandc_logo2.PNG" />
      </Head>
      <main className={styling.mainBody}>
        <div className={styling.body}> 
          <Image width={500} height={500} src='/heros-page.png' alt='real fast logo' className={styling.heroSection}/> 
          <div className={styling.heroSection2}> 
              <h1 className={styling.content}><b>ABOUT</b></h1>
              <p className={styling.content2}>I'm a Dedicated FrontEnd Developer</p>
          </div>
      
        </div>    
        <div className={styling.detailsOnPage}>
          <ul>
            <h1 style={{fontSize:'30px', paddingTop:'6px'}}>Who AM I</h1>
              <li className={styling.details}>My Mission
                is the provition of excelent result to the client,I are dedicated to the comiting to delivering to sepecification of the client . Whether it's dilever quality user interface,
             </li>
            </ul>
        </div>
      </main>
    </>
    )
  }

  const styling = {
    mainBody:'relative bg-[#272829] flex flex-col items-center',
    body:' w-[100%] h-screen l:w-[1349px] relative absolute top-0',
    heroSection:'w-[100%] h-screen  ',
    heroSection2:'flex flex-col justify-center items-center w-[100%] h-[100%] l:w-[1349px] bg-[#000]/80 absolute top-0 ',
    heroSection2Content:'flex flex-col text-center justify-center items-center',
    content:'text-[60px] text-white',
    content2:'text-white text-[20px] text-reading',
    detailsOnPage:'h-[500px] w-[500px] flex justify-center bg-gray-900 text-center text-white text-[20px] text-reading',

  }
