import Head from 'next/head';
import Image from 'next/image';


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" 
        href="/tandc_logo2.PNG" />
      </Head>
      <main>
        <div className={styling.body}> 
          <Image width={500} height={500} src='/hero-section.png' alt='real fast logo' className={styling.heroSection}/> 
          <div className={styling.heroSection2}> 
            <ul className={styling.heroSection2Content}>
              <li style={{fontSize:25,color:'white'}}>HI, I'M A FREELANCER</li>
              <li style={{fontSize:60,color:'white'}}>React Developer</li>
            </ul>
            <div className={styling.heroBtnDiv}>
              <button className={styling.heroBtn} style={{}}>Projects</button> 
              <button className={styling.heroBtn} style={{backgroundColor:'none'}}>Contacts</button> 
            </div> 
          </div>
        </div>
      </main>
    </>
    )
  }

  const styling = {
    body:' w-auto h-screen l:w-[1349px] relative',
    heroSection:'w-[100%] h-screen  ',
    heroSection2:'flex flex-col justify-center items-center w-[100%] h-[100%] l:w-[1349px] bg-[#000]/80 absolute top-0 z-[5]',
    heroSection2Content:'flex flex-col items-center',
    heroBtnDiv:'flex flex-row justify-center items-center gap-3 w-80 h-16',
    heroBtn:'w-[100%] h-[100%] text-[30px] bg-orange-600 border border',
  }
